### About Dataset
Small Subset of Dataset of Book reviews from Amazon Kindle Store Category.
Contains 982619 entries.

Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.

- asin - ID of the product
- helpful - helpfulness rating of the review
- overall - rating of the product
- reviewText - text of the review (heading)
- reviewTime - time of the review (raw)
- reviewerID - ID of the reviewer
- reviewerName - name of the reviewer
- summary - summary of the review (description)
- unixReviewTime - unix Timestamp


Output Feature -- rating


### Inspiration 
- Sentiment analysis on reviews
- Understanding how people rate usefulness of a review/What factors influence helpfulness of a review
- Fake reviews / outliers
- Best rated product IDs, or similarity between products based on review alone

### **Best Practises**
1. Preprocessing and Cleaning
2. Train Test Split
3. BOW, TF-IDF, Word2Vec
4. ML Algorithm Training

In [39]:
# Load the dataset
import pandas as pd
data=pd.read_csv("Kindle Reviews/all_kindle_review.csv",index_col=0)

In [40]:
data.head()

,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [41]:
data.columns

Index(['Unnamed: 0', 'asin', 'helpful', 'rating', 'reviewText', 'reviewTime',
       'reviewerID', 'reviewerName', 'summary', 'unixReviewTime'],
      dtype='object')

In [42]:
data.drop(columns=['Unnamed: 0'],inplace=True)

In [43]:
data.head()

,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [44]:
data.shape

(12000, 9)

In [45]:
# For now we dont need IDs and Timestamps
# Since we are trying to get the rating (output) from the reviewText (maybe we can also consider summary)

In [46]:
data["reviewText"].isnull().sum()

0

In [47]:
import nltk

In [48]:
from nltk.stem import WordNetLemmatizer
import re
lm=WordNetLemmatizer()

In [49]:
from nltk.corpus import stopwords

In [50]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\agarw\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [13]:
# Will Apply BOW First
review_corpus=[]
for i in range(data.shape[0]):
    review=re.sub("[^A-Za-z]"," ",data["reviewText"][i])
    review=review.lower()
    review_words=review.split()
    review_words=[lm.lemmatize(word) for word in review_words if word not in set(stopwords.words("english"))]
    review=" ".join(review_words)
    review_corpus.append(review)

In [51]:
review_corpus

['jace rankin may short nothing mess man hauled saloon undertaker know famous bounty hunter oregon shot man saloon finished year long quest avenge sister murder trying figure next snotty nosed farm boy rescued gang bully offer money kill man forced ranch reluctantly agrees bring man justice kill outright first need tell sister widower news kyla kyle springer bailey riding trail sleeping ground past month trying find jace want revenge man killed husband took ranch amongst crime keen detour jace want take realizes option hide behind boy persona best try keep pace confrontation along way get shot jace discovers kyle kyla come clean whole reason need scoundrel dead hope still help book share touching moment slow blooming romance kyla find good reason fear men hide behind boy persona watching jace slowly pull shell help conquer fear endearing pain real deeply rooted disappear face sexiness neither understandable aversion marriage magically disappear round nookie would man drifted town town entire adult life man killed fair share men along way feel make good husband father walking wounded unique position help need time realize however packed bursting favorite theme old west setting heroine passing male morally ambiguous hero wounded soul road romance kitchen sink certain distance writing kept getting carried away character distinct fully formed point glaring instance bland telling anything never felt really invested enjoyed quite bit exciting trip watching far away definitely run alongside add hasty tidy ending book left feeling bit less completely satisfied enjoyed book say average still read another book author note read released ebook version noticed lot formatting error missing word mentally edit read sentence make sense bad little distracting',
 'great short read want put read one sitting sex scene great two male one female character bit surprising never thought could learned something new really enjoyed reading book great way get hot bothered take advantage significant',
 'start saying first four book expecting conclude center child alex younger brother argus alex friend sapphire find name bus map find mystery start well written good character development although lot room still quite short book moving onto book swiftly',
 'aggie angela lansbury carry pocketbook instead writing light murder mystery laced misdirection clue lead rather obvious cliche ending setting view described story best believable part aggie well written character light reading',
 'expect type book library pleased find price right',
 'aislinn little girl big dream death older brother decides follow footstep become lady knight quest knighthood brings many challenge temptation forbidden love aislinn learns knight mean putting kingdom front personal concern helping cannot help journey fraught danger filled adventure aislinn forced grow fast must stay strong develop skill necessary realize lifelong dream sword fight passionate love mythical creature courtly game woman honor kind book love idea incorporating real history fantasy m zoltack book based real life story group female knight blending history fiction writing full plot adventure character strong believable grew love cared hardship success aislinn quite main protagonist tenacious bold beautiful strong romance bloom prince well developed year solid friendship teasing enjoyed reading secret courtship idea romance would turn m zoltack twist store shock startle well please conclusion thoroughly recommend book everyone enjoys fantasy romance adventure eagerly awaiting sequel knight glory',
 'making good story unfortunately disappoints tell two alpha member unfriendly pack grown together one gay straight seems get together something happens story told alternating chapter past present story couple fall apart switch time lack sustainable reason break',
 'got like collaborated short story alot time two good writer put head together result turn well case short story writer take age old lesson turn good read begin call crazy picking hitchhiker get graphic little much taste cut nutcase hitchhiking inevitably get together result suspenseful ending felt well deserved account also watched video two author decided break short story idea cool one wrote side scenario scenario without talking tier side going came bring two piece together made fit perfectly think took great talent two author take two seperate story merge well story pretty graphic detail forwarned mind little detail short story definitely pick one',
 'loved book hooked series hope kelsey maxwell really made character get enough',
 'good thing short sweet tease give everything quick kick kick come dark',
 'received copy book review secret society fanatical cult telepathic girl cup tea expected really need another continuational book still read catching fire hunger game get sci fi stuff cup tea sorry',
 'even though already know outcome still enjoyable erotic read little short taste',
 'read review decided give try despite review labeling brutal believe reviewer called brutal beyond disturbing read almost anything recognizing fiction returned less star rating available would used',
 'finished read wicked garden say wow even novella lorelei james write story hot e reader start smokin wicked garden short story lost love reuniting little extra sumthin sumthin billy buchanan return spearfish favor business associate agreed favor also would give chance ignite spark high school flame eden lacroix past ten year regretted walking away eden eden spent last ten year building career dedicated local community center helping risk kid time real relationship occasional string attached hook ups sexy native american rock star jon white feather billy eden see first time ten year chemistry spike chart eden determined fight billy working project could destroy job quickly sweet talk seeing side project thing heat eden billy realizing still strong feeling dunh dunh dunh jon come home couple day billy jon decide want give eden one darkest fantasy boy boy hot menage really like eden even though worried heart billy leaving take charge sexuality scared go want sexually much liked eden story billy jon stole story men sexy strong billy possessive sexy dominant vulnerable absolutely adore way treat eden insecurity display jon oh favorite get wrong love billy way jon treat eden menage melt heart among thing mention jon sexy rock star moon excited jon getting novella ballroom blitz release date folk let tell could get action went work room wicked garden would work room five ten time day wicked garden great novella perfect afternoon want escape hour bonus get see sexy lorelei writes non cowboy yep cowboy hat suit m james know write sexy hell hero',
 'king james version far tell may know kjv published book included get ebook kjv apocrypha kindle bible kjv apocrypha best navigation direct verse jump orking james bible apocryphaorking james bible apocryphafor want read commentary book provided short intro misbach refer either halley bible handbookhalley bible handbook new international version deluxe editionor new unger bible handbookthe new unger bible handbook available kindle ebooks',
 'disappointed book anything blond one figured joke good laugh wrong first count real surprised even joke book second among possible joke least repeated time different part book almost writer kept running list joke heard real concern whether might already recorded decided must least joke finally perfectly frank recall laughing single one joke better described insult mistaking degradation group people humor th grade material bother one worth cent even worth free',
 'super quick book wish would longer really liked character sexy bedroom pool table sex good author',
 'many time author going get amazon delete add comment alleged conspiracy people get f delusional review agree previous reviewer author know basic mechanic writing world written full star page filled grammar problem story suffers problem author inattention detail character inconsistent action like interchangeable peg board author put place need',
 'love j r ward book story completely awsome zsadist favorite series',
 'first author thoroughly enjoyed say concept dragon elf djinn war new there usually truce place elf djinn team eliminate dragon mate attempt wipe dragon race refreshing read story wise mean scarlet pop star hiding year janos dragon also elder scarlet mate janos must protect till impregnate accomplished change thus giving way protect story short page still lot told short space looking forward continuing saga next book',
 'first anya bast book really liked looked read book seems little far fetched make book different menage story author took time really develop character men got know woman claim wisk screw like bunny took time woo loved respected honored also loved fact quite way book actually sex great read one would highly recommend would loved action intrigue part loved hope book becomes series great job m bast',
 'love reading mini novel go wrong jane porter yet another great read amazingly talented author fell love estrella beautiful strong compassionate determined carlo man want hate instead end wishing enjoyed book beginning end character personality draw story line make want reach help less fortunate highly recommend mini novel perfect marriage love hate romance philanthropy',
 'book extremely incredible read much heated passion describe every steele relationship glad brother cousin found passionate love last',
 'difference guy man willingness take risk relationship woman course hot hot physical attraction explosive enjoyable earn star genre earned th star quality characterization interaction various character book book quick short read right palate pleaser want bit romance sex want commit',
 'gave half way much repetition much make sense hard follow',
 'know expecting way form fashion book exciting think ordered wrong book accident',
 'love read simon wood book one morbid make reader victim skin crawl much guessing outright gruesome',
 'short story confusing issue unreliable narrator difficult tell happening story writing poor reader able draw conclusion virtually everybody story difficulty relating others conversation begin trail without important information related author prevent normal interaction u able judge character one difficult understanding normal human interaction problem actually assumed main character mentally unbalanced waiting develop throughout story however story ended apparently become normal making unfulfilling conclusion set weird situation short story foreshadowing leave unexplored unexplained way author advance story tell u simple sentence type people character thing like nice person liked people know way never shown anything action story people put situation weird trailing conversation subjected basic statement type people environment realistic either odd wording thought first maybe story set another country character mention michigan sense place got story know michigan city hope anything specific place independent office supply story still business afford pay ten dollar hour part time help modern time hope anything specific happening character seem know thing would know example character war returned home worked another type job later old bruise face thought character war however human healing work way human aware bruise even old one relatively recent old trauma experience reading story kind like another specie writing human interaction know act way elephant interaction might make sense proofreading better earlier review stated going guess issue corrected still professional job',
 'found book enjoyable read first chapter really take keep entertained end enjoyed much immediately purchased next two book series',
 'amy parker going hawaii week christmas business give sex relationship focus career justin garrett traveling companion associate law firm work together definitely plane boldly masturbates seat next supposedly napping hears everything make hard left trip accidentally found racy email friend laptop know want know deepest darkest desire plan something hawaii meet client mitch magruder justin apprenticed going current job mitch justin share friendly camaraderie justin know count mitch help fulfill amy fantasy two work get amy relax unwind justin get relax enough give heart unwrapped jaci burton paint vivid picture two men coaxing amy letting go letting seduce reader enjoy molten hot eacute nage scene exquisite feeling finally intimate someone fantasized year m burton book power packed emotion sensuality love style creates believable intelligent character unwrapped suck page one keep riveted end highly recommended kiss pepper f eacute nage anal sex lindyreviewer twolips review llc',
 'jodi birthday last place want stuck working bos boyfriend insists night job completed little choice jodi bos may mattress dancing decided early would string attached relationship lately jodi second thought relationship mark sound really good thing get interesting jodi get busted breaking entering sinfully sexy man mark rodriguez merge security company old buddy sam favor ask sam first mark would like sam join fulfilling jodi eacute nage fantasy birthday surprise however mark start second thought see jodi sam together perhaps mark want jodi string well private property spicy erotic novella eacute nage quite birthday surprise jodi mark jodi sam heat thing lusty novel like mark immediately reconsidering idea eacute nage relationship nothing like seeing woman getting another man make realize serious private property leave thinking breaking entering might bad thing mirandafor joyfully reviewed',
 'interesting historic value really story rather accounting event interesting biographical information st person',
 'book detailed interesting felt time character much erotic got bored place tired savannah get book especially free good read',
 'rd book second time still good exciting loving story sharing making sacrifice love life easy',
 'type love ghost story enjoy book however someone else may enjoy never let people opinion put trying book look interesting said kind story',
 'believe listed romance read romance novel looking something uplifting book dark depressing find story writing bad depressing sex high overview go depth developement character relationship spoiler alert like happy ending forget said review guess strongly enough truly understand hopefully say plainly enough others expectation waste time hero dy brutal death saving heroine book continues several chapter showing remaining character pick life go end heroine sitting porch contemplating life wondering lie ahead man love gone almost cry end anger wasted free time reading book',
 'read book twice make sure happy thought knew short book bought actually felt bad finsihed story line great charcters well thought however wish longer less rush get book finished',
 'awesomee thriller hitched beginning dragged along roller coaster ride way end book great twist turn fell inlove main character girlfriend highly recommend',
 'ok story thought character little shallow pull brought together way fast booked moved sexy end blink felt like chapter get point maybe story taken place literally one place felt like really room growth story ended however well written term format would give another book author read',
 'great twist turning mystery plot unable stop reading end definitely must read mystery suspense reader definitely recommend',
 'think series first type story see james bond based bulldog drummond',
 'book wrong many level although usually type spoiler one hope daughter one scientist lab wolfe held although mark refuse mate age lab burn wolfe believed dead year hope alone unable move another man bond hope evil mother apparently know wolfe survived sending photo hope men fake course wolfe appears nowhere capture hope punishes teasing sex allowing orgasm due mating heat apparently writhing pain continues try getting answer seek find nothing wrong get worse first time stick as finally decides innocent want relieve might rough animal surface course begs orgasm forgiven joking mother show quick falling sandbag thing take joke writing even good sex attempt story thrown',
 'story written badly struck emotionally tone deaf fiction abuse whether physical emotional take u place difficult place unfamiliar maybe sadly familiar story found thinking people act way think way thing little pat little rushed language bit careless observation little bit hard specify exactly seemed story almost reading collection story written somebody much exposure father child dynamic watching lifetime movie marathon',
 'another light hearted novel hard put henry wright delightful character get tight spot',
 'never read author thoroughly enjoyed story would gladly read another disfigured hero fear pain pride wonderfully described felt wanting reach gently touch scar reassure exactly time aidan touched warwick get wrong warwick brutally strong hot male character privy thought within story began get protective feeling aidan acquired saw extremely handsome man warwick really passion romace well mixed much strengh wit character sometimes sure real hero story everyone like strong take matter hand heroine definately book one woman rescue squad perfect match mysterious masked hired guard warwick sex hot wicked well enjoy',
 'book deserving winner prestigious giller prize wanting read time wanted read boyden first book three day road first good book one even better good read three day road first precursor one helped understand character bit like three day road book difficult read way keep waiting terrible cataclysmic thing happen even though know going happen make less terrible book also similar three day road told viewpoint two different people young niece annie terrible story tell heals sharing highly recommend book would suggest read three day road first feel richer experience enjoying superlative story telling book take everyday life magical world seems real reading',
 'amazon curse built relationship event developed vampire bride showalter book stand alone much better know back story rating would different already connected character reading previous book vampire bride focus layel king vampire delilah amazon warrior however introduced many character including zane nola happy find story ended would suggest using book alone introduction showalter writing missing',
 'fan bound heart series perhaps best review book try two since reader romantic book see much romance sharing',
 'stop reading series love character jacob especially victor relationship well plot always good bit mystery going adventure get know victor past voice usual something look forward',
 'loved series seeing story family member together convenient best',
 'like dragon free download gave try aside needing editing least proofreading clear clunky storytelling found disappointed story start slow work unevenly burst action end conclusion blue jump premise dragonseer saga series halfway download half turned preview first full length dragoneers book even knowing prequel even knowing novella hoped complete self contained tale amounted overlong prologue bother preview novella accurate indicator author style sense story already know dragonseer saga reading list anytime soon',

In [91]:
from nltk.tokenize import sent_tokenize

In [92]:
for i, sent in enumerate(review_corpus):
    if len(sent_tokenize(sent)) == 0:
        print(i, repr(sent))

In [93]:
len(review_corpus)

12000

In [94]:
# # Other way to do this
# # Special Function simple_preprocess

# from gensim.utils import simple_preprocess
# words=[]
# for sent in review_corpus:
#     sent_token=sent_tokenize(sent)
#     for sent in sent_token:
#       words.append(simple_preprocess(sent))

In [95]:
# Dependent Feature (Label - Output feature)
y=data["rating"]
y

0        3
1        5
2        3
3        3
4        4
        ..
11995    4
11996    5
11997    3
11998    1
11999    3
Name: rating, Length: 12000, dtype: int64

In [96]:
data.isnull().sum(axis=0)

asin               0
helpful            0
rating             0
reviewText         0
reviewTime         0
reviewerID         0
reviewerName      38
summary            2
unixReviewTime     0
dtype: int64

In [97]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(review_corpus,y,test_size=0.20)

In [98]:
# X_train

In [ ]:
## Will use word2vec , train a word2vec, and use avgword2vec
# Review the steps first from SPAM_HAM word2vec trainer

In [85]:
# Classification using TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=2500,ngram_range=(2,3))

In [86]:
# Independent Feature
X_train=tfidf.fit_transform(X_train).toarray()
X_test=tfidf.transform(X_test).toarray()

In [87]:
# tfidf.vocabulary_

In [88]:
# Algorithm
from sklearn.naive_bayes import MultinomialNB
rating_detect=MultinomialNB()
rating_detect.fit(X_train,y_train)

MultinomialNB()

In [89]:
y_pred=rating_detect.predict(X_test)

In [90]:
# Performance Check
from sklearn.metrics import accuracy_score,classification_report
print("%.2f"%accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.43
              precision    recall  f1-score   support

           1       0.49      0.42      0.45       399
           2       0.43      0.26      0.33       425
           3       0.37      0.19      0.25       389
           4       0.35      0.58      0.44       577
           5       0.54      0.57      0.56       610

    accuracy                           0.43      2400
   macro avg       0.44      0.41      0.41      2400
weighted avg       0.44      0.43      0.42      2400

In [67]:
# cv.vocabulary_

In [26]:
# Algorithm
from sklearn.naive_bayes import MultinomialNB
rating_detect=MultinomialNB()
rating_detect.fit(X_train,y_train)

MultinomialNB()

In [27]:
y_pred=rating_detect.predict(X_test)

In [28]:
# Performance Check
from sklearn.metrics import accuracy_score,classification_report
print("%.2f"%accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.51
              precision    recall  f1-score   support

           1       0.53      0.59      0.56       408
           2       0.40      0.37      0.38       391
           3       0.35      0.34      0.35       364
           4       0.49      0.46      0.47       605
           5       0.65      0.67      0.66       632

    accuracy                           0.51      2400
   macro avg       0.48      0.49      0.49      2400
weighted avg       0.50      0.51      0.50      2400

In [32]:
# Algorithm
from sklearn.svm import SVC
rating_detect=SVC()
rating_detect.fit(X_train,y_train)

SVC()

In [33]:
y_pred=rating_detect.predict(X_test)

In [34]:
# Performance Check
from sklearn.metrics import accuracy_score,classification_report
print("%.2f"%accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.50
              precision    recall  f1-score   support

           1       0.56      0.56      0.56       408
           2       0.40      0.31      0.35       391
           3       0.45      0.22      0.30       364
           4       0.43      0.57      0.49       605
           5       0.58      0.66      0.62       632

    accuracy                           0.50      2400
   macro avg       0.49      0.46      0.46      2400
weighted avg       0.49      0.50      0.48      2400